export type OvalSizeTrans = {
  fromWidthRatio: number;
  fromHeightRatio: number;
  fromMinFillRatio: number;
  fromMaxFillRatio: number;
  fromMaxOffsetX: number;
  fromMaxOffsetY: number;
  fromRecordTime: number;
  time: number;
  toRecordTime: number;
};

export type BankTask = {
  label: string;
  color: string;
  recordSecond: number;
  flashSecond: number;
  zipFilename: string;
  isVideo: boolean;
  ovalWidthRatio: number;
  ovalHeightRatio: number;
  ovalCenterYRatio?: number;
  ovalOffsetYRatio?: number;
  minFillRatio?: number;
  maxFillRatio?: number;
  maxOffsetX?: number;
  maxOffsetY?: number;
  confidenceThreshold?: number;
  resolutionX?: number;
  resolutionY?: number;
  photoResolutionX?: number;
  photoResolutionY?: number;
  videoResolutionX?: number;
  videoResolutionY?: number;
  videoRotate90CW?: boolean;
  videoAdaptivePortrait?: boolean;
  videoBitsPerSecond?: number;
  videoTimesliceMs?: number;
  isTurnFace?: boolean;
  showFullFramePreview?: boolean;
  ovalSizeTrans?: OvalSizeTrans;
  enableBrightnessGate?: boolean;
  enableFlashCoverageGate?: boolean;
  brightnessGateMinY?: number;
  brightnessGateMaxY?: number;
  manualCameraSettings?: { colorTemperature?: number };
};

export type BankId = "VPB" | "BIDV" | "VCB" | "DAB" | "VIB" | "VTB" | "KTB" | "STB" | "SCB";

export type ModeOption = {
  id: string;
  kind: "generic" | "bank";
  label: string;
  color: string | null;
};

export const MODE_OPTIONS: ModeOption[] = [
  { id: "noflash", kind: "generic", label: "noflash", color: null },
  { id: "red", kind: "generic", label: "red", color: "#ff0000" },
  { id: "orange", kind: "generic", label: "orange", color: "#ff8000" },
  { id: "VPB", kind: "bank", label: "VPB", color: "grey" },
  { id: "BIDV", kind: "bank", label: "BIDV", color: "grey" },
  { id: "VCB", kind: "bank", label: "VCB", color: "grey" },
  { id: "DAB", kind: "bank", label: "DAB", color: "grey" },
  { id: "VIB", kind: "bank", label: "VIB", color: "grey" },
  { id: "VTB", kind: "bank", label: "VTB", color: "grey" },
  { id: "KTB", kind: "bank", label: "KTB", color: "grey" },
  { id: "STB", kind: "bank", label: "STB", color: "grey" },
  { id: "SCB", kind: "bank", label: "SCB", color: "grey" },
];

export const BANKS: Record<BankId, BankTask[]> = {
  VCB: [
    {
      label: "NoFlash",
      color: "Grey",
      recordSecond: 5,
      flashSecond: -1,
      zipFilename: "VCB_face_1",
      resolutionX: 900,
      resolutionY: 1200,
      isVideo: true,
      ovalWidthRatio: 0.5,
      ovalHeightRatio: 0.6,
    },
    {
      label: "White",
      color: "#FFFFFF",
      recordSecond: 5,
      flashSecond: 0,
      zipFilename: "VCB_face_2",
      resolutionX: 1080,
      resolutionY: 1440,
      isVideo: true,
      ovalWidthRatio: 0.75,
      ovalHeightRatio: 0.85,
    },
    {
      label: "Red",
      color: "#FF0000",
      recordSecond: 5,
      flashSecond: 0,
      zipFilename: "VCB_face_3",
      resolutionX: 1080,
      resolutionY: 1440,
      isVideo: true,
      ovalWidthRatio: 0.75,
      ovalHeightRatio: 0.85,
    },
    {
      label: "Blue",
      color: "#0000FF",
      recordSecond: 5,
      flashSecond: 0,
      zipFilename: "VCB_face_4",
      resolutionX: 1080,
      resolutionY: 1440,
      isVideo: true,
      ovalWidthRatio: 0.75,
      ovalHeightRatio: 0.85,
    },
    {
      label: "Green",
      color: "#00FF00",
      recordSecond: 5,
      flashSecond: 0,
      zipFilename: "VCB_face_5",
      resolutionX: 1080,
      resolutionY: 1440,
      isVideo: true,
      ovalWidthRatio: 0.75,
      ovalHeightRatio: 0.85,
    },
  ],
  DAB: [
    {
      label: "Standard",
      color: "Grey",
      recordSecond: 5,
      flashSecond: -1,
      zipFilename: "DAB_Face_Standard",
      isVideo: true,
      photoResolutionX: 1440,
      photoResolutionY: 1920,
      videoResolutionX: 1920,
      videoResolutionY: 1440,
      videoRotate90CW: true,
      videoBitsPerSecond: 1_000_000,
      ovalWidthRatio: 0.45,
      ovalHeightRatio: 0.5,
      ovalCenterYRatio: 2.3,
      minFillRatio: 0.9,
    },
  ],
  VIB: [
    {
      label: "Far",
      color: "#FFFFFF",
      recordSecond: 4,
      flashSecond: 0,
      zipFilename: "VIB_Face_Far",
      resolutionX: 1080,
      resolutionY: 1440,
      isVideo: true,
      ovalWidthRatio: 0.45,
      ovalHeightRatio: 0.55,
      ovalCenterYRatio: 1.8,
    },
    {
      label: "Near",
      color: "#FFFFFF",
      recordSecond: 4,
      flashSecond: 0,
      zipFilename: "VIB_Face_Near",
      resolutionX: 1080,
      resolutionY: 1440,
      isVideo: true,
      ovalWidthRatio: 0.65,
      ovalHeightRatio: 0.75,
      ovalCenterYRatio: 1.8,
    },
    {
      label: "Flash_Grey",
      color: "#808080",
      recordSecond: 4,
      flashSecond: 0,
      zipFilename: "VIB_Face_Flash_Grey",
      resolutionX: 1080,
      resolutionY: 1440,
      isVideo: true,
      ovalWidthRatio: 0.65,
      ovalHeightRatio: 0.75,
      ovalCenterYRatio: 1.8,
    },
    {
      label: "Flash_Orange",
      color: "#FF8000",
      recordSecond: 4,
      flashSecond: 0,
      zipFilename: "VIB_Face_Flash_Orange",
      resolutionX: 1080,
      resolutionY: 1440,
      isVideo: true,
      ovalWidthRatio: 0.65,
      ovalHeightRatio: 0.75,
      ovalCenterYRatio: 1.8,
    },
  ],
  BIDV: [
    {
      label: "NoFlash",
      color: "Grey",
      recordSecond: 5,
      flashSecond: -1,
      zipFilename: "BIDV_NoFlash",
      resolutionX: 1080,
      resolutionY: 1440,
      isVideo: true,
      ovalCenterYRatio: 2.6,
      ovalWidthRatio: 0.5,
      ovalHeightRatio: 0.6,
    },
    {
      label: "White",
      color: "#FFFFFF",
      recordSecond: 5,
      flashSecond: 0,
      zipFilename: "BIDV_White",
      resolutionX: 1080,
      resolutionY: 1440,
      isVideo: true,
      ovalWidthRatio: 0.65,
      ovalHeightRatio: 0.75,
    },
    {
      label: "Red",
      color: "#FF0000",
      recordSecond: 5,
      flashSecond: 0,
      zipFilename: "BIDV_Red",
      resolutionX: 1080,
      resolutionY: 1440,
      isVideo: true,
      ovalWidthRatio: 0.65,
      ovalHeightRatio: 0.75,
    },
    {
      label: "Blue",
      color: "#0000FF",
      recordSecond: 5,
      flashSecond: 0,
      zipFilename: "BIDV_Blue",
      resolutionX: 1080,
      resolutionY: 1440,
      isVideo: true,
      ovalWidthRatio: 0.65,
      ovalHeightRatio: 0.75,
    },
    {
      label: "Green",
      color: "#00FF00",
      recordSecond: 5,
      flashSecond: 0,
      zipFilename: "BIDV_Green",
      resolutionX: 1080,
      resolutionY: 1440,
      isVideo: true,
      ovalWidthRatio: 0.65,
      ovalHeightRatio: 0.75,
    },
  ],
  VTB: [
    {
      label: "NoFlash",
      color: "Grey",
      recordSecond: 5,
      flashSecond: -1,
      zipFilename: "VTB_face_1",
      resolutionX: 1080,
      resolutionY: 1440,
      isVideo: true,
      ovalWidthRatio: 0.6,
      ovalHeightRatio: 0.7,
    },
    {
      label: "White",
      color: "#FFFFFF",
      recordSecond: 5,
      flashSecond: 0,
      zipFilename: "VTB_face_2",
      resolutionX: 1080,
      resolutionY: 1440,
      isVideo: true,
      ovalWidthRatio: 0.6,
      ovalHeightRatio: 0.7,
    },
    {
      label: "Red",
      color: "#FF0000",
      recordSecond: 5,
      flashSecond: 0,
      zipFilename: "VTB_face_3",
      resolutionX: 1080,
      resolutionY: 1440,
      isVideo: true,
      ovalWidthRatio: 0.6,
      ovalHeightRatio: 0.7,
    },
    {
      label: "Blue",
      color: "#0000FF",
      recordSecond: 5,
      flashSecond: 0,
      zipFilename: "VTB_face_4",
      resolutionX: 1080,
      resolutionY: 1440,
      isVideo: true,
      ovalWidthRatio: 0.6,
      ovalHeightRatio: 0.7,
    },
    {
      label: "Green",
      color: "#00FF00",
      recordSecond: 5,
      flashSecond: 0,
      zipFilename: "VTB_face_5",
      resolutionX: 1080,
      resolutionY: 1440,
      isVideo: true,
      ovalWidthRatio: 0.6,
      ovalHeightRatio: 0.7,
    },
  ],
  VPB: [
    {
      label: "Frontal",
      color: "Grey",
      recordSecond: 5,
      flashSecond: -1,
      zipFilename: "VPB_Frontal",
      resolutionX: 1080,
      resolutionY: 1440,
      isVideo: false,
      ovalWidthRatio: 0.5,
      ovalHeightRatio: 0.6,
    },
    {
      label: "Left",
      color: "Grey",
      recordSecond: 5,
      flashSecond: -1,
      zipFilename: "VPB_Left",
      resolutionX: 1080,
      resolutionY: 1440,
      isVideo: false,
      isTurnFace: true,
      minFillRatio: 0.7,
      ovalWidthRatio: 0.5,
      ovalHeightRatio: 0.6,
    },
    {
      label: "Right",
      color: "Grey",
      recordSecond: 5,
      flashSecond: -1,
      zipFilename: "VPB_Right",
      resolutionX: 1080,
      resolutionY: 1440,
      isVideo: false,
      isTurnFace: true,
      minFillRatio: 0.7,
      ovalWidthRatio: 0.5,
      ovalHeightRatio: 0.6,
    },
  ],
  STB: [
    {
      label: "NoFlash",
      color: "Grey",
      recordSecond: 5,
      flashSecond: -1,
      zipFilename: "STB_01",
      resolutionX: 1080,
      resolutionY: 1440,
      isVideo: true,
      ovalWidthRatio: 0.6,
      ovalHeightRatio: 0.7,
    },
    {
      label: "White",
      color: "#FFFFFF",
      recordSecond: 5,
      flashSecond: 0,
      zipFilename: "STB_07_white",
      resolutionX: 1080,
      resolutionY: 1440,
      isVideo: true,
      ovalWidthRatio: 0.6,
      ovalHeightRatio: 0.7,
    },
    {
      label: "Red",
      color: "#FF0000",
      recordSecond: 5,
      flashSecond: 0,
      zipFilename: "STB_07_red",
      resolutionX: 1080,
      resolutionY: 1440,
      isVideo: true,
      ovalWidthRatio: 0.6,
      ovalHeightRatio: 0.7,
    },
    {
      label: "Blue",
      color: "#0000FF",
      recordSecond: 5,
      flashSecond: 0,
      zipFilename: "STB_07_blue",
      resolutionX: 1080,
      resolutionY: 1440,
      isVideo: true,
      ovalWidthRatio: 0.6,
      ovalHeightRatio: 0.7,
    },
    {
      label: "Green",
      color: "#00FF00",
      recordSecond: 5,
      flashSecond: 0,
      zipFilename: "STB_07_green",
      resolutionX: 1080,
      resolutionY: 1440,
      isVideo: true,
      ovalWidthRatio: 0.6,
      ovalHeightRatio: 0.7,
    },
  ],
  SCB: [
    {
      label: "Far",
      color: "#FFFFFF",
      recordSecond: 10,
      flashSecond: -1,
      zipFilename: "SCB_Face_Far",
      resolutionX: 1080,
      resolutionY: 1920,
      photoResolutionX: 1080,
      photoResolutionY: 1920,
      videoResolutionX: 1080,
      videoResolutionY: 1920,
      videoRotate90CW: false,
      isVideo: true,
      ovalWidthRatio: 0.65,
      ovalHeightRatio: 0.45,
      ovalCenterYRatio: 2.1,
      ovalOffsetYRatio: 0.02,
      minFillRatio: 0.78,
      maxFillRatio: 1.05,
      maxOffsetX: 70,
      maxOffsetY: 90,
      confidenceThreshold: 0.65,
      showFullFramePreview: true,
    },
    {
      label: "Near",
      color: "#FFFFFF",
      recordSecond: 10,
      flashSecond: -1,
      zipFilename: "SCB_Face_Near",
      resolutionX: 1080,
      resolutionY: 1920,
      photoResolutionX: 1080,
      photoResolutionY: 1920,
      videoResolutionX: 1080,
      videoResolutionY: 1920,
      videoRotate90CW: false,
      isVideo: true,
      ovalWidthRatio: 0.95,
      ovalHeightRatio: 0.75,
      ovalCenterYRatio: 2.0,
      ovalOffsetYRatio: 0.02,
      minFillRatio: 0.9,
      maxFillRatio: 1.12,
      maxOffsetX: 30,
      maxOffsetY: 40,
      confidenceThreshold: 0.6,
      showFullFramePreview: true,
      ovalSizeTrans: {
        fromWidthRatio: 0.65,
        fromHeightRatio: 0.45,
        fromMinFillRatio: 0.78,
        fromMaxFillRatio: 1.05,
        fromMaxOffsetX: 70,
        fromMaxOffsetY: 90,
        fromRecordTime: 1000,
        time: 500,
        toRecordTime: 0,
      },
    },
  ],
  KTB: [
    {
      label: "NoFlash",
      color: "Grey",
      recordSecond: 5,
      flashSecond: -1,
      zipFilename: "KTB_NoFlash",
      videoResolutionX: 1280,
      videoResolutionY: 720,
      videoRotate90CW: true,
      videoAdaptivePortrait: true,
      videoBitsPerSecond: 2_000_000,
      videoTimesliceMs: 200,
      isVideo: true,
      ovalWidthRatio: 0.9,
      ovalHeightRatio: 0.675,
      ovalCenterYRatio: 2.0,
      ovalOffsetYRatio: 0,
      minFillRatio: 0.82,
      maxFillRatio: 0.95,
      maxOffsetX: 50,
      maxOffsetY: 60,
      confidenceThreshold: 0.5,
      brightnessGateMinY: 40,
      brightnessGateMaxY: 150,
      enableBrightnessGate: true,
      manualCameraSettings: { colorTemperature: 3500 },
    },
    {
      label: "Green",
      color: "#1FBF46",
      recordSecond: 5,
      flashSecond: 0,
      zipFilename: "KTB_Green",
      videoResolutionX: 1280,
      videoResolutionY: 720,
      videoRotate90CW: true,
      videoAdaptivePortrait: true,
      videoBitsPerSecond: 2_000_000,
      videoTimesliceMs: 200,
      isVideo: true,
      ovalWidthRatio: 0.9,
      ovalHeightRatio: 0.675,
      ovalCenterYRatio: 2.0,
      ovalOffsetYRatio: 0,
      minFillRatio: 0.82,
      maxFillRatio: 0.95,
      maxOffsetX: 50,
      maxOffsetY: 60,
      confidenceThreshold: 0.5,
      brightnessGateMinY: 40,
      brightnessGateMaxY: 150,
      enableFlashCoverageGate: true,
      manualCameraSettings: { colorTemperature: 3500 },
    },
    {
      label: "Blue",
      color: "#371EC8",
      recordSecond: 5,
      flashSecond: 0,
      zipFilename: "KTB_Blue",
      videoResolutionX: 1280,
      videoResolutionY: 720,
      videoRotate90CW: true,
      videoAdaptivePortrait: true,
      videoBitsPerSecond: 2_000_000,
      videoTimesliceMs: 200,
      isVideo: true,
      ovalWidthRatio: 0.9,
      ovalHeightRatio: 0.675,
      ovalCenterYRatio: 2.0,
      ovalOffsetYRatio: 0,
      minFillRatio: 0.82,
      maxFillRatio: 0.95,
      maxOffsetX: 50,
      maxOffsetY: 60,
      confidenceThreshold: 0.5,
      brightnessGateMinY: 40,
      brightnessGateMaxY: 150,
      enableFlashCoverageGate: true,
      manualCameraSettings: { colorTemperature: 3500 },
    },
    {
      label: "Magenta",
      color: "#E63587",
      recordSecond: 5,
      flashSecond: 0,
      zipFilename: "KTB_Magenta",
      videoResolutionX: 1280,
      videoResolutionY: 720,
      videoRotate90CW: true,
      videoAdaptivePortrait: true,
      videoBitsPerSecond: 2_000_000,
      videoTimesliceMs: 200,
      isVideo: true,
      ovalWidthRatio: 0.9,
      ovalHeightRatio: 0.675,
      ovalCenterYRatio: 2.0,
      ovalOffsetYRatio: 0,
      minFillRatio: 0.82,
      maxFillRatio: 0.95,
      maxOffsetX: 50,
      maxOffsetY: 60,
      confidenceThreshold: 0.5,
      brightnessGateMinY: 40,
      brightnessGateMaxY: 150,
      enableFlashCoverageGate: true,
      manualCameraSettings: { colorTemperature: 3500 },
    },
    {
      label: "Gold",
      color: "#FFCF0C",
      recordSecond: 5,
      flashSecond: 0,
      zipFilename: "KTB_Gold",
      videoResolutionX: 1280,
      videoResolutionY: 720,
      videoRotate90CW: true,
      videoAdaptivePortrait: true,
      videoBitsPerSecond: 2_000_000,
      videoTimesliceMs: 200,
      isVideo: true,
      ovalWidthRatio: 0.9,
      ovalHeightRatio: 0.675,
      ovalCenterYRatio: 2.0,
      ovalOffsetYRatio: 0,
      minFillRatio: 0.82,
      maxFillRatio: 0.95,
      maxOffsetX: 50,
      maxOffsetY: 60,
      confidenceThreshold: 0.5,
      brightnessGateMinY: 40,
      brightnessGateMaxY: 150,
      enableFlashCoverageGate: true,
      manualCameraSettings: { colorTemperature: 3500 },
    },
  ],
};

export function isBankId(value: string): value is BankId {
  return value in BANKS;
}

export function isHexColor(color: string) {
  return color.startsWith("#");
}

export function flashCssColor(color: string): string | null {
  if (!color || color.toLowerCase() === "grey" || color.toLowerCase() === "gray") {
    return null;
  }
  return color;
}
